In [1]:
import torch
import numpy as np

/home/mcb/users/rdeng4/.local/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
shape = (5,6)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [10]:
print(rand_tensor.shape)
x = rand_tensor[None,:]
print(x.shape)
print(x.squeeze().shape)

torch.Size([5, 6])
torch.Size([1, 5, 6])
torch.Size([5, 6])


In [3]:
# matrix multiplication
t = torch.rand(4,3)
t_dot = t @ t.T
t_dot

tensor([[0.8376, 0.4407, 0.7487, 0.8131],
        [0.4407, 0.7628, 0.2859, 0.3662],
        [0.7487, 0.2859, 0.7190, 0.8474],
        [0.8131, 0.3662, 0.8474, 1.2179]])

In [4]:
t_dot2 = torch.matmul(t,t.T)
t_dot2

tensor([[0.8376, 0.4407, 0.7487, 0.8131],
        [0.4407, 0.7628, 0.2859, 0.3662],
        [0.7487, 0.2859, 0.7190, 0.8474],
        [0.8131, 0.3662, 0.8474, 1.2179]])

In [5]:
y = torch.rand_like(t_dot2,dtype=torch.float)
y

tensor([[0.6197, 0.2240, 0.6050, 0.1390],
        [0.0987, 0.5041, 0.3448, 0.8693],
        [0.3663, 0.5095, 0.5321, 0.7316],
        [0.3559, 0.0209, 0.9396, 0.0428]])

In [6]:
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
# device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
y = y.to(device) # assign device is not in-place operation
y.device

device(type='cuda', index=1)

In [7]:
print(torch.cuda.is_available())
device = 'cuda:9' if torch.cuda.is_available() else 'cpu'
device
y= y.to(device)

True


KeyboardInterrupt: 

In [ ]:
all_gpus = [torch.cuda.device(i) for i in range(torch.cuda.device_count())]
all_gpus

In [ ]:
t = torch.ones(5,5)
n = t.numpy()
print(f"tensor: {t}")
print(f"nparray: {n}")

tensor: tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
nparray: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# modify one element in tensor will reflec to numpy
t.add_(5)
print(f"tensor: {t}")
print(f"nparray: {n}")

tensor: tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]])
nparray: [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
# compute matrix multiplcation of tensors on different devices? -> NOPE!
torch.manual_seed(2022)
x = torch.rand(100,1000)
y = torch.rand(100,1000)


In [ ]:
device_x = "cuda:1" if torch.cuda.is_available() else "cpu"
# device_y = "cuda:1" if torch.cuda.is_available() else "cpu"

x * y

tensor([[0.1560, 0.0830, 0.2464,  ..., 0.0827, 0.2023, 0.1228],
        [0.1430, 0.0262, 0.0149,  ..., 0.3519, 0.4522, 0.1458],
        [0.7867, 0.0691, 0.0080,  ..., 0.1037, 0.1238, 0.8713],
        ...,
        [0.3835, 0.2374, 0.0570,  ..., 0.2310, 0.1252, 0.4348],
        [0.4538, 0.2960, 0.8927,  ..., 0.4959, 0.1861, 0.1260],
        [0.0053, 0.0064, 0.1681,  ..., 0.2121, 0.1864, 0.4741]])

In [ ]:
x = x.to(device_x)
y = y.to(device_x)
x * y

RuntimeError: CUDA error: an illegal memory access was encountered