In [23]:
import torch
from torch.nn import Linear, Softmax, ReLU,Flatten


In [29]:
torch.manual_seed(2022)
t1 = torch.rand(1,5,5) # img shape, 1 stands for chanels
t1

tensor([[[0.3958, 0.9219, 0.7588, 0.3811, 0.0262],
         [0.3594, 0.7933, 0.7811, 0.4643, 0.6329],
         [0.6689, 0.2302, 0.8003, 0.7353, 0.7477],
         [0.5585, 0.6226, 0.8429, 0.6105, 0.1248],
         [0.8265, 0.2117, 0.8574, 0.4282, 0.3964]]])

In [37]:
f = Flatten()
t2 = f(t1)
ll = Linear(25,10)
t3 = ll(t2)
sm = Softmax(dim=1)
t4 = sm(t3)

print(t3)
print(t4)


tensor([[ 0.3817,  0.5187, -0.0767,  0.1003, -0.2203,  0.2215,  0.1340, -0.5782,
         -0.4475, -0.1362]], grad_fn=<AddmmBackward>)
tensor([[0.1403, 0.1609, 0.0887, 0.1059, 0.0768, 0.1195, 0.1095, 0.0537, 0.0612,
         0.0836]], grad_fn=<SoftmaxBackward>)
